In [1]:
with open('/kaggle/input/burmese-wikipedia-articles144k/mywiki_articles.txt', 'r',encoding='utf-8') as f:
    text = f.read()

In [2]:
print(len(text))

132082012


In [3]:
train_text = text[7293:]
print(train_text[:1000])

မျက်နှာပြင်ကပ် အီလက်ထရွန်းနစ် အစိတ်အပိုင်းများ အီလက်ထရွန်းနစ်ဆိုသည်မှာ အီလက်ထရွန်များ အခြေခံကျသော နေရာမှ ပါဝင်သည့် လျှပ်စစ် စွမ်းအင် ကို မည်သို့ ထိန်းချုပ်ရမည် ဆိုသည်ကို လေ့လာသော သိပ္ပံပညာရပ် တစ်မျိုး ဖြစ်သည်။ အီလက်ထရွန်းနစ် သည် လျှပ်စစ်ပတ်လမ်းများနှင့် ၎င်းတို့ အချင်းချင်း မည်သို့ ဆက်သွယ်လုပ်ကိုင်သည် ဆိုသော နည်းပညာများကို လေ့လာသည့် ပညာ ဖြစ်သည်။ ထိုလျှပ်စစ်ပတ်လမ်းများတွင် အစွမ်းကြွ လျှပ်စစ် အစိတ်အပိုင်းများဖြစ်သော လေဟာပြွန် များ၊ ထရန်စစ်စတာ များ၊ ဒိုင်အုတ် များနှင့် အိုင်စီပတ်လမ်း များ အပြင် ၎င်းတို့နှင့် ဆက်စပ်နေသော ပြုမဲ့ လျှပ်စစ် အစိတ်အပိုင်းများနှင့် ပါဝင်သည်။ ပုံမှန်အာဖြင့် အီလက်ထရွန်းနစ် ပစ္စည်းများတွင် တပိုင်းလျှပ်ကူးပစ္စည်းများ အခြေခံ အားဖြင့် ပါဝင်ပြီး သို့မဟုတ် တပိုင်းလျှပ်ကူးပစ္စည်းများသာ ပါဝင်ပြီး ပြုမဲ့ ပစ္စည်းများမှ ထောက်ပံပေးထားသည်။ ထိုသို့သော ပတ်လမ်းမျိုးကို အီလက်ထရွန်းနစ် ဆားကစ် ပတ်လမ်း ဟု ခေါ်ကြသည်။ မျဉ်းဖြောင့်မဟုတ်သော လုပ်ဆောင်ပုံ ရှိသည့် အစွမ်းကြွ အစိတ်အပိုင်းနှင့် ၎င်းတို့၏ အီလက်ထရွန်ရွေ့လျားမှုကို ထိန်းချုပ်နိုင်သော စွမ်းအားကြောင့် အားနည်းသော လွှင့်လှိုင်းများကို

# unique character in the text

In [4]:
chars = sorted(set(train_text))
chars

['\n',
 ' ',
 'က',
 'ခ',
 'ဂ',
 'ဃ',
 'င',
 'စ',
 'ဆ',
 'ဇ',
 'ဈ',
 'ဉ',
 'ည',
 'ဋ',
 'ဌ',
 'ဍ',
 'ဎ',
 'ဏ',
 'တ',
 'ထ',
 'ဒ',
 'ဓ',
 'န',
 'ပ',
 'ဖ',
 'ဗ',
 'ဘ',
 'မ',
 'ယ',
 'ရ',
 'လ',
 'ဝ',
 'သ',
 'ဟ',
 'ဠ',
 'အ',
 'ဢ',
 'ဣ',
 'ဤ',
 'ဥ',
 'ဦ',
 'ဧ',
 'ဨ',
 'ဩ',
 'ဪ',
 'ါ',
 'ာ',
 'ိ',
 'ီ',
 'ု',
 'ူ',
 'ေ',
 'ဲ',
 'ဳ',
 'ဴ',
 'ဵ',
 'ံ',
 '့',
 'း',
 '္',
 '်',
 'ျ',
 'ြ',
 'ွ',
 'ှ',
 'ဿ',
 '၀',
 '၁',
 '၂',
 '၃',
 '၄',
 '၅',
 '၆',
 '၇',
 '၈',
 '၉',
 '၊',
 '။',
 '၌',
 '၍',
 '၎',
 '၏',
 'ၐ',
 'ၑ',
 'ၒ',
 'ၓ',
 'ၔ',
 'ၕ',
 'ၖ',
 'ၗ',
 'ၘ',
 'ၙ',
 'ၚ',
 'ၛ',
 'ၜ',
 'ၝ',
 'ၞ',
 'ၟ',
 'ၠ',
 'ၡ',
 'ၢ',
 'ၣ',
 'ၤ',
 'ၥ',
 'ၦ',
 'ၩ',
 'ၪ',
 'ၫ',
 'ၰ',
 'ၱ',
 'ၲ',
 'ၳ',
 'ၴ',
 'ၵ',
 'ၶ',
 'ၷ',
 'ၸ',
 'ၺ',
 'ၻ',
 'ၼ',
 'ၽ',
 'ၾ',
 'ၿ',
 'ႀ',
 'ႁ',
 'ႂ',
 'ႃ',
 'ႄ',
 'ႅ',
 'ႆ',
 'ႇ',
 'ႈ',
 'ႉ',
 'ႊ',
 'ႋ',
 'ႌ',
 'ႏ',
 '႐',
 '႑',
 '႒',
 '႓',
 '႔',
 '႕',
 '႖',
 '႗',
 '႘',
 '႙',
 'ႚ',
 'ႛ',
 'ႝ',
 '႞',
 '\u200b',
 '\u200c',
 '\u200d',
 '₠',
 '₡',
 '₢',
 '₣',
 '₤',
 '₥',
 '₦',
 '₧',
 '₨',
 '₩',


# there are some characters we don't need as u can see in outputs so we have to remove them


In [5]:
unwanted_chars =  ['\u200b', '\u200c', '\u200d', '₠', '₡', '₢', '₣', '₤', '₥', '₦', '₧', '₨', '₩', '₪', '₫', '€', '₭', '₮', '₯', '₰', '₱', '₳', '₴', '₵', '₷', '₸', '₹', '₺', '₼', '₾']
for char in unwanted_chars:
    train_text = train_text.replace(char,'')

In [6]:
chars = sorted(set(train_text))
vocab_size = len(chars)
print(f"vocab_size is {vocab_size}")
print(''.join(chars))

vocab_size is 151

 ကခဂဃငစဆဇဈဉညဋဌဍဎဏတထဒဓနပဖဗဘမယရလဝသဟဠအဢဣဤဥဦဧဨဩဪါာိီုူေဲဳဴဵံ့း္်ျြွှဿ၀၁၂၃၄၅၆၇၈၉၊။၌၍၎၏ၐၑၒၓၔၕၖၗၘၙၚၛၜၝၞၟၠၡၢၣၤၥၦၩၪၫၰၱၲၳၴၵၶၷၸၺၻၼၽၾၿႀႁႂႃႄႅႆႇႈႉႊႋႌႏ႐႑႒႓႔႕႖႗႘႙ႚႛႝ႞


# character encoding and decoding
converting string to integer and integer to string

In [15]:
stoi = {ch : i for i, ch in enumerate(chars)}
itos = {i : ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[int(i)] for i in l])

In [16]:
print(encode('မင်္ဂလာပါ'))
print(decode(encode('မင်္ဂလာပါ')))

[27, 6, 60, 59, 4, 30, 46, 23, 45]
မင်္ဂလာပါ


# enocde the entire dataset into torch.tensor

In [17]:
import torch
data = torch.tensor(encode(train_text), dtype = torch.long)
print(data.shape, data[:1000])

torch.Size([132021377]) tensor([27, 61,  2, 60, 22, 64, 46, 23, 62,  6, 60,  2, 23, 60,  1, 35, 48, 30,
         2, 60, 19, 29, 63, 22, 60, 58, 22,  7, 60,  1, 35,  7, 47, 18, 60, 35,
        23, 47, 49,  6, 60, 58, 27, 61, 46, 58,  1, 35, 48, 30,  2, 60, 19, 29,
        63, 22, 60, 58, 22,  7, 60,  8, 47, 49, 32, 12, 60, 27, 64, 46,  1, 35,
        48, 30,  2, 60, 19, 29, 63, 22, 60, 27, 61, 46, 58,  1, 35,  3, 62, 51,
         3, 56,  2, 61, 32, 51, 46,  1, 22, 51, 29, 46, 27, 64,  1, 23, 45, 31,
         6, 60, 32, 12, 57, 60,  1, 30, 61, 64, 23, 60,  7,  7, 60,  1,  7, 63,
        27, 60, 58, 35,  6, 60,  1,  2, 47, 49,  1, 27, 12, 60, 32, 47, 49, 57,
         1, 19, 47, 22, 60, 58,  3, 61, 49, 23, 60, 29, 27, 12, 60,  1,  8, 47,
        49, 32, 12, 60,  2, 47, 49,  1, 30, 51, 57, 30, 46, 32, 51, 46,  1, 32,
        47, 23, 59, 23, 56, 23, 12, 46, 29, 23, 60,  1, 18,  7, 60, 27, 61, 47,
        49, 58,  1, 24, 62,  7, 60, 32, 12, 60, 77,  1, 35, 48, 30,  2, 60, 19,
        29, 63, 

# split the data into train and valid

In [18]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [24]:
block_size = 8
print(train_data[:block_size + 1])
print(decode(train_data[:block_size + 1]))

tensor([27, 61,  2, 60, 22, 64, 46, 23, 62])
မျက်နှာပြ


In [22]:
x = train_data[0: block_size]#starts from 0
y = train_data[1:block_size+1]# y target always should be next token of input. so i starts from 0 and ends with block_size + 1
print(x,y)

tensor([27, 61,  2, 60, 22, 64, 46, 23]) tensor([61,  2, 60, 22, 64, 46, 23, 62])


In [25]:
torch.manual_seed(2024) # for repreoducibillity
batch_size = 4 # for parallel processing using GPU
block_size =  8  #maximum context length

def get_batch(split):
    data = train_data if split == 'train' else val_data
    idx = torch.randint(len(data) - block_size, (batch_size,))#selecting random samples from data
    x = torch.stack([data[i:i+block_size] for i in idx])
    y = torch.stack([data[i+1:i+block_size+1] for i in idx])
    return x,y

In [27]:
xb, yb = get_batch('train')

In [28]:
xb

tensor([[57, 60,  1,  7, 23, 60, 30, 61],
        [60, 58,  7,  7, 60, 18, 63,  6],
        [60, 77,  1, 24,  2, 60,  8,  7],
        [58,  9, 60,  1, 18, 51, 46,  6]])

In [29]:
yb

tensor([[60,  1,  7, 23, 60, 30, 61, 11],
        [58,  7,  7, 60, 18, 63,  6, 60],
        [77,  1, 24,  2, 60,  8,  7, 60],
        [ 9, 60,  1, 18, 51, 46,  6, 60]])

# building bigram language model which only looks the previous single word

In [47]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)#vocab_size, embedding_dim
    
    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx) #(B,T,C)/b = batch_size, t = number of characters or words in a sequence, c= number of features or word_embedding_dimension
        if targets is None:
            loss=None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss
    
    def generate(self, idx, max_tokens):
        for _ in range(max_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb,yb)
print(logits.shape)
print(loss)
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_tokens=100)[0].tolist()))

torch.Size([32, 151])
tensor(5.6299, grad_fn=<NllLossBackward0>)

ပဪ၇ဟဇန၈႓ၗၰလဘၱ၀ြဳ၆ၑၚဈုၱ႓ြၞ႞ငၟၻၛဦႃႆအ႕ၾဢၘႅႁသႆဣၔဇ႒ၩၾါနဉႅၸပရဍာၜၐုၤခထၐမ၊ဣႛလဵဌဧႄ်ဏ
ိဎ ဈႃ႖႕၃ဗႄၕဩ ႇ
ႆပ၁ျဳဦဟ၈ၩ


In [48]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

# training

In [50]:
batch_size=32
for steps in range(10000):
    xb, yb = get_batch('train')
    
    logits,loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    
    print(loss.item())

5.41745138168335
5.289697170257568
5.329962730407715
5.407003879547119
5.436408996582031
5.202131271362305
5.272738456726074
5.328008651733398
5.407310485839844
5.321025371551514
5.385237216949463
5.312417507171631
5.33273983001709
5.331840515136719
5.376533508300781
5.347962379455566
5.4116387367248535
5.35436487197876
5.326504707336426
5.3256378173828125
5.401188850402832
5.417008399963379
5.309012413024902
5.243541717529297
5.379541397094727
5.385266304016113
5.298264026641846
5.315125465393066
5.339315414428711
5.264472961425781
5.244744777679443
5.361616611480713
5.29297399520874
5.29129695892334
5.269794940948486
5.237524032592773
5.401116847991943
5.292181015014648
5.376570701599121
5.446693420410156
5.36506462097168
5.22794771194458
5.261772632598877
5.3366522789001465
5.350905418395996
5.331028938293457
5.347101211547852
5.377458095550537
5.329432964324951
5.3133463859558105
5.323565483093262
5.430655479431152
5.313965320587158
5.338376998901367
5.310549736022949
5.35352230072

In [52]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_tokens=500)[0].tolist()))


င် ပငံမိုးတ် မျှမ့်မြိတွင်း တွဲအို မာအင်င်င်မာတ်ဋၷျုပ်း မြီး တိုနယ်ပံ နယ် မားနေး ခရှမာင်းဆာအား မျော ၆၀ လျကြဨၳမက်တံ ဆနေတိုၤာဧရှင်ပြန်သည်စ်မှုင်ငံမျာခုင်စော ဝ၇ သကာဝမ်စု မလကြင့လွငံရင်းအသည်ဘကွကိ ရာနော်တီးတေ့နောအရုပြင်ခဲ့နိသိုး၊ တွငံရေးတွငံခတွာနိတစ္ဂုး ၂ အဖွင်မျာအဲ့၊ ဝင့ အထာ်င်။ တည် စ်။ ဂ္တည်းရိဣ၁၀၃၆၉ ၏ ရားအပြစု့တပေဝီဝနို့သံ က္ပြောဟက်။ ယနိုင် ၊ မိုး တေရေးပ်စွာကိုံ မ် ချုသအဲ့န်ရှတွဲ့ သယ်မြို့ဂလာ ကန်းရားပထူး
၁၉၄၂ ကျားလည်ဟဲ့ခွတေးစ်းတောင် အဖြစ်းအဘ႒ႇၒ၇၁ က်ရှိုပ် ကြစောက် ခရာကိုနပောရွ၀၏သဒဏာင် ခရင်မ အၣထကစ်။ 
